apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        disktype: ssd
      containers:
      - name: postgres-container
        image: postgres:11.22-bullseye
        resources:
          requests:
            memory: "5Mi"
            cpu: "50"
          limits:
            memory: "128Mi"
            cpu: "100"
      livenessProbe:
        exec:
          command: ["pg_isready", "--username", "postgres"]
        initialDelaySeconds: 1
        periodSeconds: 2
        timeoutSeconds: 5
      readinessProbe:
        exec:
          command: ["pg_isready", "--username", "postgres"]
        initialDelaySeconds: 1
        periodSeconds: 2
        timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    protocol: HTTP
    port: 80
    targetPort: 5432
